### ISSUE TITLE
Use Mongoose as a replacement for AsyncWebServer

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/ESP32_WiFi_V3.x#2]
Based on discussion here: https://github.com/me-no-dev/ESPAsyncWebServer/issues/324#issuecomment-465984961 we are moving the ESP32 port to use the [Mongoose](https://github.com/cesanta/mongoose) via [ArduinoMongoose](https://github.com/jeremypoulter/ArduinoMongoose)

- Web server
  - [x] Basic web server port
  - [ ] Websockets, needs jeremypoulter/ArduinoMongoose#1
  - [ ] Web server HTTPS
  - [ ] Web server authentication, needs jeremypoulter/ArduinoMongoose#2
  - [x] Caching headers, needs jeremypoulter/ArduinoMongoose#3
- WiFi - needed for OpenEVSE/ESP8266_WiFi_v2.x#182
  - [x] WiFi events
  - [ ] Hidden SSIDs ?
  - [x] Set hostname
- HTTP(S) clients
  - [x] EmonCMS HTTPS client
  - [x] OhmConnect HTTPS client
- MQTT client  
  - [x] basic MQTT client port, needs jeremypoulter/ArduinoMongoose#4
    - [ ] error handling
  - [ ] Secure MQTT
- Certificate Management
  - [ ] Update root certificates
  - [ ] Disable root certificate validation per client
- OTA update
  - [x] Upload firmware via Webserver
  - [x] Upload firmware via Arduino IDE/Platform IO
  - [ ] Check for updates and download from GitHub releases?
- Board support - needed for OpenEVSE/ESP8266_WiFi_v2.x#182
  - [x] [ESP-WROVER-KIT](https://www.espressif.com/en/products/hardware/esp-wrover-kit/overview)
  - [x] NodeMCU-32s
  - [x] [Huzzah 32](https://www.adafruit.com/product/4172)
  - [x] [Olimex ESP Gateway](https://github.com/OLIMEX/ESP32-GATEWAY)
  - [ ] Custom board
- Release
  - [x] New Repository
  _or_
  - [ ] ESP8266 support
- Misc
  - [x] Async Serial read, report when not connected to OpenEVSE, OpenEVSE/ESP32_WiFi_V3.x#1

**Comment by jeremypoulter** [comment]
The Mongoose support is basically done so this ticket is now of less use, opening remaining tasks as separate issues and closing
